version: '2'
services:
  node:
    build: .
    ports:
      - 8080:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command:
      - npm
      - run
      - start
volumes:
  node_modules:
