version: '2'
services:
  node:
    build: .
    ports:
      - 8080:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command:
      - dev
    links:
      - postgres:postgresql
  postgres:
    restart: always
    image: postgres:9.6.1
    ports:
      - 5400:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  node_modules:
  pg-data: